on:
  push:
  pull_request:
  workflow_call:

name: CI
jobs:
  test:
    if: false # skip as the example structure has changed with v1.1.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datacontract-cli[all]
          datacontract --version
      - name: Validate examples
        run: .github/validate-examples
